CREATE TABLE IF NOT EXISTS websites(
    id                      UUID PRIMARY KEY,
    user_id                 UUID REFERENCES users(id) ON DELETE CASCADE UNIQUE,
    is_local_dev_enabled    BOOLEAN DEFAULT FALSE,
    url                     VARCHAR,
    name                    VARCHAR,
    status                  VARCHAR,
    created_at              TIMESTAMPTZ,
    updated_at              TIMESTAMPTZ
);